kind: Deployment
apiVersion: apps/v1
metadata:
  name: gym-web
  namespace: negrdo
  labels:
    k8s-app: gym-web
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gym-web
  template:
    metadata:
      name: gym-web
      labels:
        k8s-app: gym-web
    spec:
      containers:
        - name: gym-web
          image: cesar9504/gym-web:<IMAGE_TAG>
          resources:
            limits:
              memory: "300Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "200m"

          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - medium

---
kind: Service
apiVersion: v1
metadata:
  name: gym-web
  namespace: negrdo
  labels:
    k8s-app: gym-web
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30996
  selector:
    k8s-app: gym-web
  type: NodePort