ARG NODE_VERSION=20.9.0
FROM node:${NODE_VERSION} AS build
WORKDIR /app
COPY package.json .
RUN npm install
COPY nginx.conf .
COPY . /app

COPY config.staging.js /app/src/services/config.js

RUN npm run build

FROM nginx:latest
COPY --from=build /app/build usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

#docker build -f Dockerfile.prod -t negrdo-distributions .
#docker run -d -p 3000:80 --name idtolu-production idtolu-frontend